// 资料层：初始示例数据（相对今天生成，保证演示时影像时效始终真实）
import { addDaysISO, todayISO } from "./dates";
import type { SurgeryCase } from "./types";

export function buildSeedCases(): SurgeryCase[] {
  const today = todayISO();
  const d = (offset: number) => addDaysISO(today, offset);

  return [
    {
      id: "c-36",
      patientName: "张敏",
      toothNo: "#36",
      diagnosis: "慢性根尖周炎伴瘘管",
      imageDate: d(-4),
      anesthesia: "confirmed",
      schedule: null,
      operative: null,
      review: null,
      status: "pending",
    },
    {
      id: "c-11",
      patientName: "李建国",
      toothNo: "#11",
      diagnosis: "根尖周囊肿（根管治疗后）",
      imageDate: d(-54),
      anesthesia: "confirmed",
      schedule: null,
      operative: null,
      review: null,
      status: "pending",
    },
    {
      id: "c-21",
      patientName: "王雪",
      toothNo: "#21",
      diagnosis: "根管治疗失败、根尖暗影",
      imageDate: d(-6),
      anesthesia: "unconfirmed",
      schedule: null,
      operative: null,
      review: null,
      status: "pending",
    },
    {
      id: "c-46",
      patientName: "陈涛",
      toothNo: "#46",
      diagnosis: "近中双根管，急性根尖周脓肿",
      imageDate: null,
      anesthesia: "unconfirmed",
      schedule: null,
      operative: null,
      review: null,
      status: "pending",
    },
    {
      id: "c-12",
      patientName: "刘芳",
      toothNo: "#12",
      diagnosis: "外伤后慢性根尖周炎",
      imageDate: d(-2),
      anesthesia: "confirmed",
      schedule: { date: d(1), slot: "AM", microscopeId: "M1" },
      operative: null,
      review: null,
      status: "scheduled",
    },
    {
      id: "c-26",
      patientName: "赵磊",
      toothNo: "#26",
      diagnosis: "根管超填伴根尖炎症",
      imageDate: d(-10),
      anesthesia: "confirmed",
      schedule: { date: d(3), slot: "PM", microscopeId: "M2" },
      operative: null,
      review: null,
      status: "scheduled",
    },
    {
      id: "c-16",
      patientName: "孙倩",
      toothNo: "#16",
      diagnosis: "牙髓坏死、大面积根尖暗影",
      imageDate: d(-18),
      anesthesia: "confirmed",
      schedule: { date: d(-14), slot: "AM", microscopeId: "M1" },
      operative: {
        surgeryDate: d(-14),
        apicoLengthMm: 3,
        retrofillMaterial: "MTA",
        specimenNo: "SP-20260910-16",
      },
      review: null,
      status: "operated",
    },
    {
      id: "c-35",
      patientName: "吴琳",
      toothNo: "#35",
      diagnosis: "慢性根尖周炎",
      imageDate: d(-42),
      anesthesia: "confirmed",
      schedule: { date: d(-35), slot: "PM", microscopeId: "M2" },
      operative: {
        surgeryDate: d(-35),
        apicoLengthMm: 2.5,
        retrofillMaterial: "iRoot BP Plus",
        specimenNo: "SP-20260820-35",
      },
      review: {
        reviewedAt: d(-21),
        painResolved: true,
        defectChange: "healing",
        notes: "瘘管闭合，嘱冠修复。",
      },
      status: "reviewed_ok",
    },
    {
      id: "c-45",
      patientName: "郑海",
      toothNo: "#45",
      diagnosis: "根尖周肉芽肿",
      imageDate: d(-40),
      anesthesia: "confirmed",
      schedule: { date: d(-30), slot: "AM", microscopeId: "M2" },
      operative: {
        surgeryDate: d(-30),
        apicoLengthMm: 3,
        retrofillMaterial: "生物陶瓷 CEM",
        specimenNo: "SP-20260825-45",
      },
      review: {
        reviewedAt: d(-16),
        painResolved: false,
        defectChange: "enlarged",
        notes: "咬合痛持续，CBCT 示暗影增大，需再次评估。",
      },
      status: "followup",
    },
  ];
}
